### ISSUE TITLE
a question about your conclusion on the increasement of SDF bias caused by more sampling points in Figure 3

### ISSUE THREAD

**Issue by laliwang** [codekansas/usa#24]
Since you have defined the distribution of the point cloud `cij` to be normal distribution centered at 1cm in your Figure 3, I just wonder why the increasement of sampling points results in the change of mean of normal distribution, which puzzled me a lot. Could you please provide additional explanations about the decreasement of the mean value of your normal distribution? Thanks a lot for your reply!

**Comment by codekansas** [comment]
Sure. Suppose you have some samples drawn from noisy sensor indicating how far away a point is. The SDF ground truth is generated by choosing the nearest neighbor point from each of the samples. So the nearest point from a bunch of samples is likely to be closer than the nearest point from a small number of samples. Does that make sense?

**Comment by laliwang** [comment]
Yes, you do have a point. Thanks for your reply!
